### PR TITLE
add white background to logos

### PR DESCRIPTION
**Pull request by flicksolutions**

### CODE REVIEW

**Comment by pdaengeli** [comment]
lgtm

**Comment by pdaengeli** [comment]
NB: similarly to [ˋtarget=_blankˋ](https://github.com/dse-as/annemarie-schwarzenbach.ch/commit/d919b21321bf03b9863a84ef07a9d3821f976913) the inline style is purged by the [action](https://github.com/wranders/markdown-to-pages-action/tree/master/src).

Might be caused  upstream (https://github.com/aleen42/markdown-only).

**Comment by flicksolutions** [comment]
is caused upstream by using the github md-rendering. This will not change. Maybe we can inject styles a different way...

**Comment by pdaengeli** [comment]
My intention was to avoid local copies of these logos and other images to keep the setup lightest-weight. But we could create our own versions of the logos with equally sized rectangles with white background. 

White-background logos on black site background wouldn't be perfect, but an improvement over what we got now (irregular shapes/sizes of logos).

**Pull request merged**
